version: '3'
services:
  #db:
    #image: postgres
  eclipse:
    #build: .
    command: docker run --rm -ti --privileged --ipc=host --env="QT_X11_NO_MITSHM=1"  -e DISPLAY=$DISPLAY \
        -v /tmp/.X11-unix:/tmp/.X11-unix \
        -v /mnt/depot/eclipseOxygen0_1/eclipseForCora/workspace:/home/$USER/workspace \
        -v /mnt/depot/eclipseOxygen0_1/eclipseForCora/eclipse:/home/$USER/eclipse \
        -v /mnt/depot/eclipseOxygen0_1/eclipseForCora/.eclipse:/home/$USER/.eclipse \
        -v /mnt/depot/eclipseOxygen0_1/eclipseForCora/m2:/home/$USER/.m2 \
        -v /mnt/depot/eclipseOxygen0_1/eclipseP2:/home/$USER/.p2 \
        -v /mnt/depot/eclipseOxygen0_1/.gitconfig:/home/$USER/.gitconfig \
        --env user=$USER -p 8080:8080 -p 9876:9876 -p 8090:8090 -p 8983:8983 --name eclipseforcoraoxogen1 eclipseforcoraoxygen1 $2
    '
    #volumes:
     # - .:/myapp
    #ports:
     # - "3000:3000"
    #depends_on:
    #  - db